[project]
authors = ["Łukasz Kalbarczyk"]
entry = "main.sw"
forc-version = "0.35.3"
license = "Apache-2.0"
name = "redstone"
organization = "Redstone"

[constants]
CONTRACT_ID = { type = "b256", value = "0xbc01b40b335d443392dad1765f446e917163b151c0a4f5eb831ccddda0f25e5c" }
