[project]
authors = ["Łukasz Kalbarczyk"]
entry = "main.sw"
forc-version = "0.38.0"
license = "Apache-2.0"
name = "redstone"
organization = "RedStone"

[dependencies]
redstone = { path = "../redstone" }
