[project]
authors = ["Łukasz Kalbarczyk"]
entry = "main.sw"
forc-version = "0.35.3"
license = "Apache-2.0"
name = "redstone"
organization = "Redstone"

[dependencies]
redstone = { path = "../redstone" }
