name: Monorepo CI - main dry run test

on:
  push:
    branches: "**"

jobs:
  build:
    runs-on: LargeRunner
    defaults:
      run:
        working-directory: packages/integration
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: bash main-dry-run-test-core.sh
        env:
          NODE_ENV: test
