name: Monorepo CI

on:
  push:
    branches: "**"

# We can integration tests for X and classic models in future

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/integration
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: bash integration-test-core.sh
        env:
          NODE_ENV: test
