name: Monorepo CI

on:
  push:
    branches: "**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/integration
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: bash integration-test.sh
        env:
          NODE_ENV: test
