name: On-chain relayer CI
on:
  push:
    paths:
      - packages/rpc-providers/**
      - .github/workflows/rpc-providers-tests.yml

jobs:
  run-tests:
    runs-on: LargeRunner
    defaults:
      run:
        working-directory: packages/rpc-providers
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: yarn
      - name: Compile contracts
        run: yarn compile
      - name: Build
        run: yarn build
      - name: Run tests
        run: yarn test
        env:
          NODE_ENV: test
